### ISSUE TITLE
When switching on, Homey reports a "switched off" directly and nothing happens

### ISSUE THREAD

**Issue by iAmRenzo** [mhaid/de.mhaid.panasonicTVIP#11]
When I switch my TV on, Homey reports a "switched off" at the same time. There isn't anything happening with my TV (screen nor led).
I can't remember if it worked: I am dismantling my HomeBridge installation, moving it all to Homey.

![IMG_1692](https://user-images.githubusercontent.com/1183790/109925288-d9d3c980-7cc1-11eb-83dc-d37e58dba74a.jpeg)

**Comment by mhaid** [comment]
Hello Renzo,

if the TV is turned off and you try to turn it on via Homey, the app will send a "Wake On LAN" request to the TV.
Unfortunatly by design I can't reviece any response from the TV, if "Wake on LAN" is even supported.

With the newest version (App V4.0.0) I implemented a error message, if the device is not turning on.

It's available for you to test here: https://homey.app/a/de.mhaid.panasonicTVIP/test/
_As I also implemented some other changes, please remove your device first, and then add it back to Homey. Otherwise it could fail to work._

Best regards,
Morris
