### ISSUE TITLE
Select specific input

### ISSUE THREAD

**Issue by mhaid** [mhaid/de.mhaid.panasonicTVIP#9]
_Is it possible to add the option hdm1 hdmi2 av enz in flows? Because the start input isn't always the same._ @Martinbugel

As soon as I have found a suitable way to implement this, I will notify you. Any help is of course welcome!

**Comment by Martinbugel** [comment]
hello, this feature doesn't work because homey is version 5 now? With version 4 there was an app that could. this means that the tv seems to support it?

**Comment by mhaid** [comment]
Hello Martin,
I had another look at it and it seems to work now for selecting a specific input (e.g. HDMI1,TV,SD-Card)

It's available for you to test here: https://homey.app/a/de.mhaid.panasonicTVIP/test/
_As I also implemented some other changes, please remove your device first, and then add it back to Homey. Otherwise it could fail to work._

Best regards,
Morris

**Comment by Martinbugel** [comment]
Hello,

Thanks! I have tested the options and it works perfect!

Regards



Verzonden vanaf mijn Galaxy



-------- Oorspronkelijk bericht --------
Van: Morris Haid ***@***.***>
Datum: 04-03-2021 12:41 (GMT+01:00)
Aan: "mhaid/de.mhaid.panasonicTVIP" ***@***.***>
Cc: Martin Bugel ***@***.***>, Mention ***@***.***>
Onderwerp: Re: [mhaid/de.mhaid.panasonicTVIP] Select specific input (#9)


Hello Martin,
I had another look at it and it seems to work now for selecting a specific input (e.g. HDMI1,TV,SD-Card)

It's available for you to test here: https://homey.app/a/de.mhaid.panasonicTVIP/test/<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fhomey.app%2fa%2fde.mhaid.panasonicTVIP%2ftest%2f&umid=9ff9a907-4b48-47f7-8025-8b0a3eefc884&auth=6d7d132172d8f584c3849cd1aa5f3ec2ba7e40fe-9611d1d108a3764544bb71551ab472ff46eb91f4>
As I also implemented some other changes, please remove your device first, and then add it back to Homey. Otherwise it could fail to work.

Best regards,
Morris
